/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IncomesImport } from './routes/incomes'
import { Route as ExpensesImport } from './routes/expenses'
import { Route as ExpenseWithReceiptImport } from './routes/expense-with-receipt'
import { Route as CreateIncomeImport } from './routes/create-income'
import { Route as CreateExpenseImport } from './routes/create-expense'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const IncomesRoute = IncomesImport.update({
  path: '/incomes',
  getParentRoute: () => rootRoute,
} as any)

const ExpensesRoute = ExpensesImport.update({
  path: '/expenses',
  getParentRoute: () => rootRoute,
} as any)

const ExpenseWithReceiptRoute = ExpenseWithReceiptImport.update({
  path: '/expense-with-receipt',
  getParentRoute: () => rootRoute,
} as any)

const CreateIncomeRoute = CreateIncomeImport.update({
  path: '/create-income',
  getParentRoute: () => rootRoute,
} as any)

const CreateExpenseRoute = CreateExpenseImport.update({
  path: '/create-expense',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/create-expense': {
      id: '/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof CreateExpenseImport
      parentRoute: typeof rootRoute
    }
    '/create-income': {
      id: '/create-income'
      path: '/create-income'
      fullPath: '/create-income'
      preLoaderRoute: typeof CreateIncomeImport
      parentRoute: typeof rootRoute
    }
    '/expense-with-receipt': {
      id: '/expense-with-receipt'
      path: '/expense-with-receipt'
      fullPath: '/expense-with-receipt'
      preLoaderRoute: typeof ExpenseWithReceiptImport
      parentRoute: typeof rootRoute
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesImport
      parentRoute: typeof rootRoute
    }
    '/incomes': {
      id: '/incomes'
      path: '/incomes'
      fullPath: '/incomes'
      preLoaderRoute: typeof IncomesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  CreateExpenseRoute,
  CreateIncomeRoute,
  ExpenseWithReceiptRoute,
  ExpensesRoute,
  IncomesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/create-expense",
        "/create-income",
        "/expense-with-receipt",
        "/expenses",
        "/incomes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/create-expense": {
      "filePath": "create-expense.tsx"
    },
    "/create-income": {
      "filePath": "create-income.tsx"
    },
    "/expense-with-receipt": {
      "filePath": "expense-with-receipt.tsx"
    },
    "/expenses": {
      "filePath": "expenses.tsx"
    },
    "/incomes": {
      "filePath": "incomes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
